### PR TITLE
revamp demon lord

### PR DESCRIPTION
**Pull request by Cokemonkey11**
Demon lord has some issues:

1. It's not very strong
2. It's a heavily mana-bound caster
3. It's a poor tank
4. Doesn't really have anything to fit the motto "Loves destruction"

I made a changes to address these.

1. Firestorm: now damages nearby units and provides bonus str for more hit, strongly encourages the player to act as a tank. Damage is all in one wave now -> much stronger.
2. Howl of terror: reduced range, increased damage reduction, added permanent bonus. Strongly encourages the player to stand in the middle of foes and kill low-health targets.

### CODE REVIEW

**Comment by Overkane** [comment]
Hi! Thanks for your PR.

Skill changes are nice, but I think skills' str bonus is too big.

Fire storm on lvl 5 will have 10 sec bonus str duration and 9 sec cd what means infinite str bonus.
Also on lvl 5 1 creep gives you 25 str. Isn't that too high just for 1 creep? 

Same goes for howl of terror. 5 str for 1 unit, considering hero has splash and fire storm, makes hero godlike killing machine.

So I think for howl of terror str bonus should be like "1-1-2-2-3" and for firestorm bonus per unit something like "3*lvl* and its cd to be just static 14 secs. And I think it wiill be good.

**Comment by Cokemonkey11** [comment]
Hey @Overkane 

Overall, happy to make the changes you're asking for, but I do think that this hero is quite weak, int casters are pretty powerful atm, and also I think it's a mistake to guess about what will be balanced without measuring anything. I measured performance in [battle planes](https://github.com/Cokemonkey11/the-gorge/blob/master/wurst/triggers/Damage.wurst), lmk if you want a PR to do that in gods arena.

Anyway, will make the changes you asked now

**Comment by Cokemonkey11** [comment]
Also on this:

> Fire storm on lvl 5 will have 10 sec bonus str duration and 9 sec cd what means infinite str bonus.

That's not quite true. You can maintain the str bonus and even get 1 second of double bonus if you keep casting the spell and hitting targets, but the bonuses are temporary

**Review by Overkane — APPROVED** [review]
Seems nice. Thank you!
Didn't get the part about battle planes though, I believe link is pointing to the gorge map?

**Comment by Cokemonkey11** [comment]
@Overkane map renamed

The link is showing how I measure what is actually overpowered, rather than guessing

**Comment by Overkane** [comment]
@Cokemonkey11 
oh, so it's some kind of dps meter?
Yeah, would be cool to see one in the multiboard in the future.

**Pull request merged**
